Feature/JC19-282 mobile layout
saritasa-nest/camp-js-2022-artem-sotnichenko pull request #11
Opened 2022-02-15 03:08 UTC by artem-sotnichenko-saritasa

2022-02-15 04:30 UTC, golovachev-yaroslav approved these changes

2022-02-15 04:30 UTC, golovachev-yaroslav commented on vanilla/src/index.html
> +        <!-- Dan's code block beginning -->
What is the valueability of this comment? Maybe remove it?

2022-02-15 05:49 UTC, panov-aleksey-saritasa approved these changes

2022-02-15 05:49 UTC, panov-aleksey-saritasa commented on vanilla/src/base.css
> +  --film-card-max-width: 480px;
I don't think this variables should be in `base.css` file since they are `film`-specific

2022-02-16 02:44 UTC, timofei-maximov-saritasa approved these changes

2022-02-16 04:16 UTC, gevorg-gevorgyan-saritasa approved these changes

2022-02-16 05:05 UTC, golovachev-yaroslav approved these changes

2022-02-16 06:46 UTC, chernodub requested changes

2022-02-16 06:46 UTC, chernodub commented on vanilla/src/index.html
> +            placeholder="Search film title..."
Your placeholder is not really suitable :) 
_It should be a word or short phrase that provides a hint as to the expected type of data, **rather than an explanation or prompt**. ... So for example if a field is expected to capture a user's first name, and its label is "First Name", a suitable placeholder might be "e.g. Mustafa"._ [link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-placeholder)

2022-02-16 06:46 UTC, chernodub commented on vanilla/src/index.html
> +              class="is-secondary pagination__prev pagination__button"
As I suggested, use modifier-classes for `pagination__button` instead of aplying two element-classes

2022-02-16 08:18 UTC, golovachev-yaroslav approved these changes

2022-02-21 03:21 UTC, merged