Feature/JC19-284 Angular initialization and authorization
saritasa-nest/camp-js-2022-artem-sotnichenko pull request #12
Opened 2022-02-21 03:23 UTC by artem-sotnichenko-saritasa

2022-02-21 03:55 UTC, panov-aleksey-saritasa commented on angular/src/app/core/services/auth.service.ts
> +    return from(signInWithPopup(this.auth, provider)).pipe(map(() => void 0));
you can use `mapTo(void 0)` for this

2022-02-21 03:55 UTC, panov-aleksey-saritasa commented on angular/src/app/core/services/auth.service.ts
> +    return from(signOut(this.auth));
Whenever you make an observable out of promise, I recommend using `defer` instead of `from` as a rule of thumb. Otherwise Promise would be called immediately, not at the time of subscription. Maybe it's not relevant for your case, but still, it's more maintainable and it's simpler to stick to one way.

2022-02-21 03:55 UTC, panov-aleksey-saritasa commented on angular/src/app/core/services/auth.service.ts
> +    );
consider using `shareReplay` here, otherwise `authState` function will be called each time you subscribe to `user$`

2022-02-21 03:55 UTC, panov-aleksey-saritasa commented on angular/src/app/features/auth/auth.component.html
> +  </button>
Missing `type` for button

2022-02-21 03:55 UTC, panov-aleksey-saritasa commented on angular/src/app/features/header/header.component.html
> +    <ng-template #unauthorized>
Please, use nouns for `ng-template` variable

2022-02-21 03:55 UTC, panov-aleksey-saritasa commented on angular/src/app/features/auth/auth.component.ts
> +    public router: Router,
Missing `readonly` modifier. And why did you make these services `public`?

2022-02-21 04:05 UTC, panov-aleksey-saritasa commented on angular/src/app/core/utils/destroyable.ts
> +
It's great that you use ready solution from our boilerplate, but I recommend you either to come up with your own solution or to investigate how does it work underhood :)

2022-02-21 04:10 UTC, chernodub requested changes

2022-02-21 04:10 UTC, chernodub commented on angular/src/app/features/header/header.component.html
> +  <div class="header__logo">sw films</div>
I'd recommend creating a component for this logo, in order to (1) separate the concerns and (2) reuse it in other places if it's ever needed

2022-02-21 04:10 UTC, chernodub commented on angular/src/app/features/header/header.component.html
> +  <div class="header__group">
Please consider giving this element more semantically valuable name, it's not really clear, what the `group` represents

2022-02-21 04:10 UTC, chernodub commented on angular/src/app/features/header/header.component.html
> +        <div class="profile__username">{{ user.name }}</div>
Usually, it's a good idea to make the name of a user to be a component. If your app ever needs a to-profile-redirection, it's gonna be very easy to support with this stuff.

2022-02-21 04:10 UTC, chernodub commented on angular/src/app/features/header/header.component.html
> +        />
I'd recommend to create a component for isolating avatar-related logic and to reuse it

2022-02-21 04:10 UTC, chernodub commented on angular/src/app/features/auth/auth.component.html
> +  </button>
Supporting only google auth is not fun, please implement an extra type of authorization, via email/password :)

2022-02-21 04:10 UTC, chernodub commented on angular/src/app/features/header/header.component.html
> +<header class="header">
The header could be isolated for your layout component so as not to make it visible for the whole app

2022-02-21 04:10 UTC, chernodub commented on angular/src/theme/styles/tokens.css
> +  --size-8: 2rem;
Your spacing should not depend on font size, otherwise, if a user increases in-system font size it's gonna mess your layout a lot

2022-02-21 04:10 UTC, chernodub commented on angular/src/theme/styles/tokens.css
> +  --font-size-lg: 32px;
Cool approach with the variables, good job!

2022-02-21 04:10 UTC, dbitkovski commented on angular/src/app/core/utils/destroyable.ts
> +// Heroically stolen from saritasa angular boilerplate.
Do you have access to our angular boilerplate? Honestly, I'd not recommend using any stuff from there because right now we want to see your solutions, not ours :)
How can we evaluate you if I see what was written by saritasa team? Especially when we're talking about rxjs. This is probably one of the hardest parts of angular and we want to be sure you really understand what's going on here

2022-02-21 04:10 UTC, dbitkovski commented on angular/src/app/features/auth/auth.component.html
> +  <button mat-stroked-button (click)="onSignInWithGoogle()">
Don't forget about `type` attribute

2022-02-21 04:10 UTC, dbitkovski commented on angular/src/app/core/services/mappers/mappers.ts
> +export interface MapperFromDto<Dto, Domain> {
Do you need to use such an interface? As I know when you add your interface you want to add an abstraction layer to allow some parts of your code to work with an interface, not a concrete class. But as I see you just get `UserMapper` in the `auth.service.ts` file. You don't use any pros of the interface.

2022-02-21 10:04 UTC, viktor-sakhno-saritasa commented on angular/src/app/shared/components/header/header.component.html
> +        class="header__button header__button--signout"
Use this structure for BEM modifiers `block-name_modifier-name`
https://en.bem.info/methodology/quick-start/#modifier

2022-02-21 10:04 UTC, viktor-sakhno-saritasa commented on angular/src/app/shared/components/header/header.component.ts
> +    this.destroy$.complete();
The same as above.

2022-02-22 03:42 UTC, chernodub requested changes

2022-02-22 03:42 UTC, chernodub commented on angular/src/app/features/header/header.component.html
> +<header class="header">
@artem-sotnichenko-saritasa I mean that you can create a layout module where you can declare parts of those layouts (e.g.: footer, header, etc) and export only the layout components (main-layout, blank-layout in your case) without exposing its parts, this way you protect your application from reusing the components that aren't supposed to be reused anywhere else.

2022-02-22 03:42 UTC, chernodub commented on angular/src/app/features/header/header.component.html
> +<header class="header">
e.g: 
```ts
@NgModule({
  declarations: [HeaderComponent, MainLayout, BlankLayout],
  exports: [MainLayout, BlankLayout]
})
export class LayoutsModule {}
```

2022-02-22 03:42 UTC, chernodub commented on angular/src/app/features/sign-in/sign-in.component.html
> +    <div hint>
Good idea with content projection! But please try prefixing it somehow with the name of the component, in order for it to be clear to where it belongs. E.g: `signInFormHint`

2022-02-22 03:42 UTC, chernodub commented on angular/src/app/shared/components/avatar/avatar.component.html
> +<img *ngIf="src" [src]="src" [alt]="alt" class="avatar" />
I believe it would be a good idea to show some avatar placeholder whenever a user doesn't have profile photo

2022-02-22 03:42 UTC, chernodub commented on angular/src/app/shared/components/blank-layout/blank-layout.component.css
> +  height: 100vh;
I'd recommend not to hardcode the height of this, what if you would want to reuse this layout in some other context where you don't have this much space?

2022-02-22 03:42 UTC, chernodub commented on angular/src/app/shared/components/header/header.component.ts
> +    this.destroy$.unsubscribe();
Since you already got the idea with subscriptions, I think you can use the `takeUntilDestroy` in order to reduce the amount of boilerplate code in your next imeplementations

2022-02-22 03:42 UTC, chernodub commented on angular/src/app/features/sign-up/sign-up.component.ts
> +  private errors: Record<string, string> = {
[Don't forget about `readonly`](https://frontendwiki.saritasa.rocks/pages/development/languages/typescript.html#promote-immutability)

2022-02-22 03:42 UTC, chernodub commented on angular/src/app/features/sign-up/sign-up.component.ts
> +    'auth/invalid-email': 'Invalid email.',
Seems like this logic is firebase-bound, wouldn't it be better to put it inside your auth service?

2022-02-22 03:42 UTC, chernodub commented on angular/src/app/shared/components/main-layout/main-layout.component.html
> +  <ng-content></ng-content>
Consider adding a heading prop for this component, I believe this would improve the accessibility of your application

2022-02-22 03:42 UTC, chernodub commented on angular/src/app/shared/components/sign-in-form/sign-in-form.component.ts
> +  public formChange = new EventEmitter<SignInForm>();
We prefer making outputs to be readonly

2022-02-22 03:42 UTC, chernodub commented on angular/src/app/shared/components/sign-in-form/sign-in-form.component.ts
> +    }
Seems like this logic can be used for other features, consider creating a reusable entity

2022-02-22 03:42 UTC, chernodub commented on angular/src/app/shared/components/sign-in-form/sign-in-form.component.ts
> +    }
This looks very similar to the getter above, again, reusing here would be a good idea :)

2022-02-22 03:42 UTC, chernodub commented on angular/src/app/shared/components/sign-in-form/sign-in-form.component.html
> +    <mat-error *ngIf="passwordError">{{ passwordError }}</mat-error>
Consider showing this only if the control wasn't yet touched by a user, forms API provides this functionality

2022-02-22 04:00 UTC, timofei-maximov-saritasa commented on angular/src/app/features/sign-in/sign-in.component.ts
> +
This logic should be in your `auth.service`. You have this logic [here](angular/src/app/features/sign-up/sign-up.component.ts)

2022-02-22 05:29 UTC, artem-sotnichenko-saritasa commented on angular/src/app/shared/components/blank-layout/blank-layout.component.css
> +  height: 100vh;
I am not sure how to make `blank-layout` take full height of the screen. 
Only solution I came with is add `:host { height: 100%; }` to `sw-sign-in` and `sw-blank-layout`, but it's bad solution isn't it?

2022-02-22 06:20 UTC, artem-sotnichenko-saritasa commented on angular/src/app/shared/components/sign-in-form/sign-in-form.component.html
> +    <mat-error *ngIf="passwordError">{{ passwordError }}</mat-error>
If I understand correctly, It is default behavior. Error shown after first blur, not initially.

2022-02-22 06:23 UTC, artem-sotnichenko-saritasa commented on angular/src/app/shared/components/main-layout/main-layout.component.html
> +  <ng-content></ng-content>
Not sure what do you mean

2022-02-22 06:36 UTC, timofei-maximov-saritasa commented on angular/src/app/app-routing.module.ts
> +  },
I guess, it should be under some `AuthModule` those modules shares some logic

2022-02-22 07:10 UTC, panov-aleksey-saritasa commented on angular/src/app/core/services/auth.service.ts
> +    'unknown': 'Unknown error.',
`string` type for keys in incorrect here, since they have limited range of values. Consider using `enum` or `union` instead

2022-02-22 10:00 UTC, panov-aleksey-saritasa commented on angular/src/app/shared/components/header/header.component.html
> +        [routerLink]="['/auth/signin']"
With your approach property binding in unnecessary here, you can rewrite it like `routerLink="/auth/signin"`

2022-02-22 10:30 UTC, artem-sotnichenko-saritasa commented on angular/src/app/features/sign-in/sign-in.component.html
> +    <div hint>
I had difficulties (cyclic dependencies) when creating `LayoutsModule` and importing it in `SharedModule`, because `HeaderComponent` requires a lot of dependencies from `SharedModule`.
On the other hand, we shouldn't move `LayoutsModule` into features because it behaves like `SharedModule`.

I isolated `HeaderComponent` by not exporting it from `SharedModule`.

2022-02-23 04:15 UTC, pavel-romanov8 requested changes

2022-02-23 04:15 UTC, pavel-romanov8 commented on angular/src/app/features/auth/sign-up/sign-up.component.ts
> +  private readonly destroy$ = new Subject<void>();
Place your private fields blow public as you did in other components

2022-02-23 04:15 UTC, pavel-romanov8 commented on angular/src/app/shared/components/profile/profile.component.ts
> +  public onSignOut(): void {
I don't see that you are using this method at all

2022-02-24 03:24 UTC, timofei-maximov-saritasa approved these changes

2022-02-24 03:24 UTC, timofei-maximov-saritasa commented on angular/src/app/features/auth/sign-up/sign-up.component.html
> +      Already have an acount? <a routerLink="/auth/signin">Sign in</a>
Typo

2022-02-24 03:24 UTC, timofei-maximov-saritasa commented on angular/src/app/core/core.module.ts
> +export class CoreModule { }
Do you really need this module? It seems, you don't use it at all.

2022-02-24 03:55 UTC, golovachev-yaroslav approved these changes

2022-02-24 11:33 UTC, panov-aleksey-saritasa commented on angular/src/app/features/auth/auth-routing.module.ts
> +  },
You can combine it into one object (place redirect route in `children` prop)

2022-02-24 11:33 UTC, panov-aleksey-saritasa commented on angular/src/app/features/auth/auth-form.component.html
> +        <ng-content select="[formHint]"></ng-content>
FYI, it's not required to wrap content of `select` attribute in square brackets

2022-02-24 11:33 UTC, panov-aleksey-saritasa commented on angular/src/app/shared/components/avatar/avatar.component.ts
> +  public alt: string | null = null;
seems unused

2022-02-24 11:33 UTC, panov-aleksey-saritasa commented on angular/src/app/shared/shared.module.ts
> +
I don't think there is any profit in splitting components and layouts in different arrays, since they both need to be declared and exported anyway. Usually we have `EXPORTED_DECLARATIONS` array in modules in which we put all things that need to be declared and exported.

2022-02-24 11:33 UTC, panov-aleksey-saritasa commented on angular/src/app/shared/components/sign-in-form/sign-in-form.component.ts
> +  });
Missing `readonly`

2022-02-25 03:22 UTC, pavel-romanov8 approved these changes

2022-02-25 03:22 UTC, pavel-romanov8 commented on angular/src/app/core/services/destroy.service.ts
> + * Observable abstraction over ngOnDestroy to use with takeUntil.
As I know this implementation is taken from the [taiga UI](https://github.com/Tinkoff/taiga-ui). It is a good thing to leave a comment about it in your docs with a link.

Plus there is some drawback when you are using the implementation. If you forget to declare the service in the component provider instance of the service will be taken from its parent. That might lead to memory leaks when your stream is still alive even though the component itself has already been destroyed.

In order to resolve this issue use `Self` decorator for each instant of the service. That way you will get an error every time you forget to provide an instance for the component.

2022-02-25 08:38 UTC, panov-aleksey-saritasa approved these changes

2022-02-25 08:38 UTC, panov-aleksey-saritasa commented on angular/src/app/core/services/destroy.service.ts
> + * Component must have providers: `[TuiDestroyService]`.
```suggestion
 * Component must have providers: `[DestroyService]`.
```

2022-02-25 10:18 UTC, dbitkovski approved these changes

2022-02-25 10:18 UTC, dbitkovski commented on angular/src/app/features/auth/auth-routing.module.ts
> +    ],
what's the point of using `children` here?

2022-02-28 10:26 UTC, chernodub approved these changes

2022-02-28 10:26 UTC, chernodub commented on angular/src/theme/styles/tokens.css
> +  --size-12: 48px;
Consider making these variables more named more specifically. It's not clear what a `size` represents in your app? Or, at least, explain it via comments

2022-02-28 12:29 UTC, artem-sotnichenko-saritasa commented on angular/src/app/shared/components/avatar/avatar.component.html
> +      inline
I used `inline` to be able to set icon size with a `font-size`.

2022-02-28 12:33 UTC, merged