Feature/JC19-284 Films page with filters
saritasa-nest/camp-js-2022-artem-sotnichenko pull request #14
Opened 2022-03-02 05:30 UTC by artem-sotnichenko-saritasa

2022-03-02 06:29 UTC, kristinaSvobodinaSaritasa commented on angular/src/app/core/services/film/film.service.ts
> +  public readonly films$: Observable<Film[]>;
Service shouldn't save this data, what will be if you need to use this service in several components?

2022-03-02 07:16 UTC, artem-sotnichenko-saritasa commented on angular/src/app/core/services/film/film.service.ts
> +  public readonly films$: Observable<Film[]>;
I use this service as a shared state in films table component (reading `films$`) and films filters component (updating films$). 
If I will need it in other components I could inject it in `providers` of component or parent module and use other instance in these components.

2022-03-02 09:33 UTC, pavel-romanov8 requested changes

2022-03-03 03:41 UTC, dbitkovski approved these changes

2022-03-04 08:53 UTC, elena-dragunova approved these changes

2022-03-05 06:30 UTC, chernodub requested changes

2022-03-05 06:30 UTC, chernodub commented on angular/src/app/core/services/film/utils/get-page-status.ts
> +  readonly forwardQueryCursorId: QueryCursorId;
Consider revising your “cursor” approach. The idea is good, but as far as I can see you're sometimes twisting the terminology in your code. You declared the `QueryCursor` to be a `DocumentSnapshot`, which is kind of logical, although it has some drawbacks I will explain later. Then, you call film ID a “cursor”. This sounds weird, since both the film ID and document snapshot are cursors?
Anyway, let me suggest you how you can do this. Firstly, check out the image attached.
<img width="606" alt="image" src="https://user-images.githubusercontent.com/37013688/156870717-719421a3-b211-40e6-9c5d-fb3c65eb8cff.png">

A cursor in this case could be an interface of `{topEntityId: string; bottomEntityId: string}`. The cursor is the entity that holds the info about the edge objects, that are needed in order for you to move back and forward. The cursor could be expanded, whenever you load a new page. Also, the cursor could hold the information about whether any of the sides have more objects to load. Following this logic, you could revise your implementation, feel free to contact the team if you have any questions.

2022-03-05 06:30 UTC, chernodub commented on angular/src/app/core/services/film/utils/get-query-constraint.ts
> +const SEARCH_SORT_FIELD = SortField.Title;
Weird name, you meant `SEARCH_FIELD`?

2022-03-05 06:30 UTC, chernodub commented on angular/src/app/core/services/film/utils/get-query-constraint.ts
> +        where(SEARCH_SORT_FIELD, '<=', `${searchText}${FIREBASE_SEARCH_SYMBOL}`),
What's the problem combining search and sort queries ?

2022-03-05 06:30 UTC, chernodub commented on angular/src/app/core/services/film/utils/get-query-constraint.ts
> +  }
This stuff is duplicated, please reuse this

2022-03-05 06:30 UTC, chernodub commented on angular/src/app/core/services/film/utils/types.ts
> +export type QueryCursor<T = DocumentData> = DocumentSnapshot<T> | '';
Wow, this is some weird union of types. How is this possible to be either an empty string or a snapshot? I could not imagine such a case

2022-03-05 06:30 UTC, chernodub commented on angular/src/app/core/services/film/utils/types.ts
> +}
Please move the extensions below the parent, this is our styleguide

2022-03-05 06:46 UTC, artem-sotnichenko-saritasa commented on angular/src/app/core/services/film/film.service.ts
> +      'films',
`fetchMany` has union type as first parameter.

2022-03-05 09:08 UTC, artem-sotnichenko-saritasa commented on angular/src/app/core/services/film/utils/get-page-status.ts
> +  readonly forwardQueryCursorId: QueryCursorId;
I discussed it with Pavel Zadorin on the meeting, he suggested the function that would take cursor argument and return films and two cursors to fetch. 

Something like `function getFilms(cursor): { films, cursors } `.

So I was in the middle of implementing it when you reviewed.

2022-03-08 10:20 UTC, artem-sotnichenko-saritasa commented on angular/src/app/core/services/film/utils/get-page-status.ts
> +  readonly forwardQueryCursorId: QueryCursorId;
I investigated how `@angular/fire` works, it caches data. So even when I go page back, in my current implementation, data is taken from cache. 
I am not sure if I have enough time to refactor my code now, I still need to implement film details page. So I will try to improve implementation if I have time left.

2022-03-10 08:06 UTC, timofei-maximov-saritasa approved these changes

2022-03-14 01:33 UTC, dbitkovski approved these changes

2022-03-14 01:39 UTC, merged