Feature/jc19 284 film details
saritasa-nest/camp-js-2022-artem-sotnichenko pull request #15
Opened 2022-03-12 13:20 UTC by artem-sotnichenko-saritasa

2022-03-14 05:14 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/film-row/film-row.component.html
> +  <a class="film-row__link" routerLink="/film/{{ id }}">{{ title }}</a>
Please, prefer `[routerLink]="['/film', id]"` syntax

2022-03-14 05:14 UTC, panov-aleksey-saritasa commented on angular/src/app/features/film/film.component.ts
> +      );
I think you should use `filter` here to check whether `id` is `null` or not. There is no much sense to work with film if it's `null` :)

2022-03-14 09:24 UTC, viktor-sakhno-saritasa commented on angular/src/app/core/services/film-details.service.ts
> +  public getFilm(id: FilmDto['id']): Observable<Film> {
I think it's not entirely correct to pass an argument of type DTO to the function that you call in the component.

2022-03-14 09:24 UTC, viktor-sakhno-saritasa commented on angular/src/app/features/film/film.component.html
> +          >
Fix format.

2022-03-14 11:26 UTC, timofei-maximov-saritasa requested changes

2022-03-14 11:26 UTC, timofei-maximov-saritasa commented on angular/src/app/core/models/planet.ts
> +  /** The terrain of this planet. Comma separated if diverse. */
Seems like outdated documentation from your `dto`.

2022-03-14 11:26 UTC, timofei-maximov-saritasa commented on angular/src/app/core/services/film-details.service.ts
> +  }
Shouldn't it be in your `FilmService`?

2022-03-14 11:26 UTC, timofei-maximov-saritasa commented on angular/src/app/core/services/film-details.service.ts
> +  }
I'm not sure, that you should fetch your related data in your `FilmDetailsService`.

2022-03-14 11:26 UTC, timofei-maximov-saritasa commented on angular/src/app/core/services/pagination.service.ts
> +      return [...films];
Do you really need it?

2022-03-15 03:00 UTC, artem-sotnichenko-saritasa commented on angular/src/app/core/services/pagination.service.ts
> +      return [...films];
Yes, I do: `The type 'readonly Film[]' is 'readonly' and cannot be assigned to the mutable type 'Film[]'`

2022-03-16 06:34 UTC, elena-dragunova approved these changes

2022-03-16 07:37 UTC, panov-aleksey-saritasa approved these changes

2022-03-17 03:23 UTC, chernodub commented on angular/src/app/core/services/mappers/character.mapper.ts
> +  switch (dto.toLowerCase()) {
Usually, the repo layer should provide something more predictable. I already suggested you to use union types for `CharacterGenderDto`, pls check it out. This way you could use a statically-typed mapping object, that would allow your IDE to track the changes of this union type and let you know whenever you need to adjust your mapping logic. 
Consider the following case, your DB now stores some third option for a gender (or whatever, this is not only about gender), now, your application is going to be silent about it, it'll just use `null` on domain layer. This is not good.

By using union typed `CharacterGenderDto`, you could create a mapper record.
```ts
const GENEDER_MAP_FROM_DTO = Readonly<Record<CharacterGenderDto, CharacterGender>> = {
  male: CharacterGender.Male,
  female: CharacterGender.Female,
};
```
So, whenever you add some new value in the `CharacterGenderDto` union, TS will tell you that your mapping needs to be changed -> (optional) domain logic needs to be adjusted. Everything is explicit.

2022-03-17 03:23 UTC, chernodub commented on angular/src/app/features/film/film.component.html
> +          >
https://frontendwiki.saritasa.rocks/pages/development/languages/html.html#title-for-controlslinks-that-do-not-contain-representative-text

2022-03-17 03:23 UTC, chernodub commented on angular/src/app/features/film/film.component.html
> +      <div class="film__description">{{ film.openingCrawl }}</div>
`p` would fit here just fine

2022-03-17 03:23 UTC, chernodub commented on angular/src/app/features/film/film.component.ts
> +        filter((id): id is string => id != null),
Consider asserting instead. Otherwise, it's going to be harder to debug the reason of non-loaded film.

2022-03-17 03:40 UTC, artem-sotnichenko-saritasa commented on angular/src/app/core/services/mappers/character.mapper.ts
> +    default:
SWAPI specifies only two options for gender, so in this case `Other` wouldn't be used. But maybe, I could use `Other` as default case, if I get anomaly data from server.

2022-03-17 03:50 UTC, artem-sotnichenko-saritasa commented on angular/src/app/core/services/mappers/character.mapper.ts
> +  switch (dto.toLowerCase()) {
I prematurely leave a comment in previous conversation, but now everything make sense.

2022-03-17 04:04 UTC, artem-sotnichenko-saritasa commented on angular/src/app/core/services/firestore/firestore.service.ts
> +    for (let i = 0; i < ids.length; i += FIRESTORE_BATCH_MAX_SIZE) {
It actually would be `reduce` rather than `map`,  I think complex `reduce` is harder to read than for loop.

2022-03-17 04:24 UTC, artem-sotnichenko-saritasa commented on angular/src/app/core/services/firestore/firestore.service.ts
> +    for (let i = 0; i < ids.length; i += FIRESTORE_BATCH_MAX_SIZE) {
The best solution that I came up with.
I think it is more complicated, so procedural approach can be justified here.
```ts
const idBatches = ids.reduce<string[][]>((batches, id, index) => {
  const batchIndex = Math.floor(index / FIRESTORE_BATCH_MAX_SIZE);

  // batches[batchIndex] = batches[batchIndex] ? [...batches[batchIndex], currentId] : [currentId];

  if (batches[batchIndex]) {
    batches[batchIndex] = [];
  }
  batches[batchIndex].push(id);

  return batches;
}, []);

const entitiesBatches = idBatches.map(
  batch => collectionData(query<T>(
    getCollection(this.db, collectionName),
    where(documentId(), 'in', batch),
  ), { idField: 'id' }),
);
```

2022-03-17 07:17 UTC, gevorg-gevorgyan-saritasa approved these changes

2022-03-18 02:32 UTC, pavel-romanov8 commented on angular/src/app/features/film/film.component.ts
> +    private readonly planetService: PlanetService,
You can initialize everything in the constructor, therefore reduce the scope of the component's dependencies to the constructor. F.e:
```ts
this.films = route.param.pipe(
   switchMap(paramMap => {
     if (paramMap.get('id') != null) {
       return filmService.getFilm(paramMap.get('id'))
     }
  })
)
```
It is always better to keep your dependencies scope as small as possible, and here you can definitely do it

2022-03-18 02:32 UTC, pavel-romanov8 commented on angular/src/app/features/film/film.component.ts
> +        switchMap(paramMap => this.filmService.getFilm(paramMap.get('id') as string)),
Please, avoid such dirty casting. The method can return `null` and you should explicitly handle the case instead of doing assertions. I provided an example of how you can do it in the comment above

2022-03-18 05:26 UTC, artem-sotnichenko-saritasa commented on angular/src/app/features/film/film.component.ts
> +        switchMap(paramMap => this.filmService.getFilm(paramMap.get('id') as string)),
Oh, I misunderstood Viktor [here](https://github.com/saritasa-nest/camp-js-2022-artem-sotnichenko/pull/15#discussion_r828721244).

2022-03-18 07:19 UTC, dbitkovski approved these changes

2022-03-18 07:51 UTC, chernodub commented on angular/src/app/core/services/firestore/firestore.service.ts
> +    for (let i = 0; i < ids.length; i += FIRESTORE_BATCH_MAX_SIZE) {
Agree 👍

2022-03-18 07:53 UTC, chernodub approved these changes
Good job!

2022-03-18 08:31 UTC, merged