Feature/JC19-296 Authorization page
saritasa-nest/camp-js-2022-artem-sotnichenko pull request #17
Opened 2022-03-17 15:41 UTC by artem-sotnichenko-saritasa

2022-03-18 01:08 UTC, thanhnguyen-saritasa commented on react/src/features/auth/pages/AuthPage/AuthPage.tsx
> +import {
Is there any way to import all material components by default for our project? so we do not need to import them in each component? please thinking about that

2022-03-18 03:23 UTC, golovachev-yaroslav approved these changes

2022-03-18 07:13 UTC, timofei-maximov-saritasa commented on react/src/features/auth/pages/AuthPage/AuthPage.tsx
> +  const handleGoogleSignInClick = useCallback(() => dispatch(signInWithGoogle()), []);
Missed dependency

2022-03-18 07:13 UTC, timofei-maximov-saritasa commented on react/src/routes/guards/AuthLoadingGuard.tsx
> +  }, [dispatch]);
I understand why you did this, but this should be handled by redux. Perhaps, there is a way to get auth state without any subscribtion?

2022-03-18 07:13 UTC, timofei-maximov-saritasa commented on react/src/routes/guards/AuthorizedOnlyGuard.tsx
> +  if (!isAuthorized) {
You can make it explicit
```ts
if (isAuthorized === false)
```

2022-03-18 08:08 UTC, chernodub commented on react/src/routes/guards/AuthorizedOnlyGuard.tsx
> +  if (!isAuthorized) {
@timofei-maximov-saritasa I think it's okay for boolean values, we usually mean not to use the implicit casting

2022-03-18 08:27 UTC, artem-sotnichenko-saritasa commented on react/src/features/auth/pages/AuthPage/AuthPage.tsx
> +      </Button>
Oh no... 😩
I asked the Pavel Zadorin, he gave a green light to implementing only social auth, because of a little time left.
I will work with forms in other features, so I think it can be omitted in current circumstances😉

2022-03-21 03:32 UTC, panov-aleksey-saritasa approved these changes

2022-03-21 03:37 UTC, golovachev-yaroslav approved these changes

2022-03-21 06:17 UTC, gevorg-gevorgyan-saritasa approved these changes

2022-03-22 18:59 UTC, pavelzadorin-saritasa requested changes

2022-03-22 18:59 UTC, pavelzadorin-saritasa commented on react/src/routes/guards/AuthLoadingGuard.tsx
> +      dispatch(setUser(user));
In my opinion, this should still be placed in dispatchers, because this is the logic for updating the state of the current user, not related directly to `AuthLoadingGuard`.
For example, we may have a thunk `fetchAuthStatus` which will be dispatched from this component and subscribe to updates.

2022-03-23 12:34 UTC, merged