Feature/JC19-290 film management
saritasa-nest/camp-js-2022-artem-sotnichenko pull request #18
Opened 2022-03-18 10:53 UTC by artem-sotnichenko-saritasa

2022-03-18 11:28 UTC, timofei-maximov-saritasa requested changes

2022-03-18 11:28 UTC, timofei-maximov-saritasa commented on angular/src/app/core/services/film-management.service.ts
> +  public getFilmByParamMap(paramMap$: Observable<ParamMap>): Observable<Film> {
I don't get it, why do you need this method? You have getFilm in your film service. I think, getFilm is enough for this situation

2022-03-18 11:28 UTC, timofei-maximov-saritasa commented on angular/src/app/core/services/film-management.service.ts
> +  public getFilmByParamMap(paramMap$: Observable<ParamMap>): Observable<Film> {
And also your service should know anything about `ParamMap`

2022-03-18 11:28 UTC, timofei-maximov-saritasa commented on angular/src/app/features/film/film-form/film-form.component.ts
> +  public readonly submitted = new EventEmitter<FilmForm>();
Let's improve `Output` naming. For example, `filmSubmit`

2022-03-18 11:28 UTC, timofei-maximov-saritasa commented on angular/src/app/features/film/film-form/film-form.component.ts
> +  public readonly canceled = new EventEmitter<void>();
Same about naming here

2022-03-18 11:28 UTC, timofei-maximov-saritasa commented on angular/src/app/shared/components/entities-select/entities-select.component.ts
> +  }
I guess it should be in constructor

2022-03-18 11:28 UTC, timofei-maximov-saritasa commented on angular/src/app/shared/components/entities-select/entities-select.component.html
> +      [value]="entity.id"
Missing `trackBy`

2022-03-21 04:52 UTC, panov-aleksey-saritasa requested changes

2022-03-21 04:52 UTC, panov-aleksey-saritasa commented on angular/src/app/core/models/film-form.ts
> +export type FilmForm = Omit<Film, 'id'>;
FYI, you can create `FilmCreateInfo` and `FilmUpdateInfo` models and then use them for creating/updating film data.

2022-03-21 04:52 UTC, panov-aleksey-saritasa commented on angular/src/app/core/services/films/films.service.ts
> +  readonly include: boolean;
Consider adding [prefix](https://frontendwiki.saritasa.rocks/pages/development/principles/naming.html#is) for your `boolean` property

2022-03-21 04:52 UTC, panov-aleksey-saritasa commented on angular/src/app/core/services/films/utils/types.ts
> +  readonly include: boolean;
Same

2022-03-21 04:52 UTC, panov-aleksey-saritasa commented on angular/src/app/features/film/create/create.component.ts
> +    // "Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?"
?

2022-03-21 04:52 UTC, panov-aleksey-saritasa commented on angular/src/app/features/film/delete-dialog/delete-dialog.component.html
> +  <button mat-button [mat-dialog-close]="true" cdkFocusInitial>Delete</button>
Missing `type` attribute for buttons

2022-03-21 04:52 UTC, panov-aleksey-saritasa commented on angular/src/app/features/film/create/create.component.ts
> +      takeUntil(this.destroy$),
about [takeUntil](https://github.com/saritasa-nest/camp-js-2022-maxim-korkin/pull/9#discussion_r829798393)

2022-03-21 04:52 UTC, panov-aleksey-saritasa commented on angular/src/app/features/film/create/create.component.ts
> +      takeUntil(this.destroy$),
You can just do it like
```ts
    this.filmService.create(filmForm);pipe(
      takeUntil(this.destroy$),
      ...
```

2022-03-21 04:52 UTC, panov-aleksey-saritasa commented on angular/src/app/features/film/create/create.component.ts
> +      }),
Prefer navigating on `next` (if you have `take(1)` or `first()`) or on `complete`

2022-03-21 04:52 UTC, panov-aleksey-saritasa commented on angular/src/app/features/film/details/film.component.ts
> +          }),
Same

2022-03-21 04:52 UTC, panov-aleksey-saritasa commented on angular/src/app/features/film/film-form/film-form.component.ts
> +  public readonly film$ = new ReplaySubject<FilmForm>();
Please, always use `bufferSize` param for replay subjects, otherwise they are going to cache every passed value

2022-03-21 04:52 UTC, panov-aleksey-saritasa commented on angular/src/app/features/film/film-form/film-form.component.ts
> +  }
[wiki](https://frontendwiki.saritasa.rocks/pages/development/angular/practices.html#do-not-subscribe-inside-a-constructor) about subscribing in constructor

2022-03-21 04:52 UTC, panov-aleksey-saritasa commented on angular/src/app/features/film/film-form/film-form.component.ts
> +  public filmForm: FormGroup = this.getFilmForm();
You don't need to use type annotation here

2022-03-21 04:52 UTC, panov-aleksey-saritasa commented on angular/src/app/features/film/film-form/film-form.component.ts
> +  }
[wiki](https://frontendwiki.saritasa.rocks/pages/development/angular/practices.html#make-your-side-effects-explicit) about side effects

2022-03-21 04:52 UTC, panov-aleksey-saritasa commented on angular/src/app/features/film/film-form/film-form.component.ts
> +        } as FilmForm);
Consider asserting that `filmForm` is not `null`

2022-03-21 04:52 UTC, panov-aleksey-saritasa commented on angular/src/app/features/film/film-form/film-form.component.ts
> +    return this.fb.group({
Usually we separate initialization phase and updating phase of form. I think there is no reason to reinitialize it every time. Consider using `patchValue` instead

2022-03-21 04:52 UTC, panov-aleksey-saritasa commented on angular/src/app/shared/components/entities-select/entities-select.component.ts
> +  public readonly changed = new EventEmitter<readonly Entity['id'][]>();
prefer using infinitive verbs for `Output` names

2022-03-21 06:03 UTC, artem-sotnichenko-saritasa commented on angular/src/app/features/film/create/create.component.ts
> +    // "Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?"
The error message that I got, I decided to use variable to explicitly subscribe in angular zone.

2022-03-21 06:07 UTC, chernodub commented on angular/src/app/features/film/update/update.component.html
> +    [allPlanets]="(planets$ | async) ?? []"
What if planets would need to be paginated (e.g. there's an autocomplete inside a form)? This is not going to be easy to implement this using inputs/outputs, therefore it would be reasonable to fetch this stuff right from `film-form`

2022-03-21 06:09 UTC, artem-sotnichenko-saritasa commented on angular/src/app/features/film/create/create.component.ts
> +      takeUntil(this.destroy$),
Router not working properly if remove variable, I get "Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?" warning, then stack on loading and need to refresh page.

2022-03-22 01:12 UTC, dbitkovski approved these changes

2022-03-22 01:12 UTC, dbitkovski commented on angular/src/app/features/film/update/update.component.ts
> +    this.location.back();
I don't know the route of this page but let's think its `/films/:id/update`.
If I open new browser tab and navigate to `yourapp.com/films/:id/update` then `location.back()` returns me back to the home page. Not an issue, just fyi

2022-03-22 02:48 UTC, artem-sotnichenko-saritasa commented on angular/src/app/features/film/film-form/film-form.component.ts
> +          producers: film.producers.split(','),
I have array in model, but form store it as a string

2022-03-22 04:55 UTC, panov-aleksey-saritasa commented on angular/src/app/features/film/create/create.component.ts
> +      takeUntil(this.destroy$),
It's not normal behavior. Please, research why this `ngZone` error is happening

2022-03-24 03:30 UTC, merged