Feature/JC19-296 Films list of films page
saritasa-nest/camp-js-2022-artem-sotnichenko pull request #19
Opened 2022-03-22 12:17 UTC by artem-sotnichenko-saritasa

2022-03-22 12:29 UTC, golovachev-yaroslav requested changes

2022-03-22 12:29 UTC, golovachev-yaroslav commented on react/src/features/films/components/FilmCard/FilmCard.module.css
> +  display: "flex";
please double quotes?

2022-03-22 12:29 UTC, golovachev-yaroslav commented on react/src/features/films/components/FilmFilter/FilmFilter.tsx
> +} from 'react';
Usually, import react lib as the first.

2022-03-22 12:29 UTC, golovachev-yaroslav commented on react/src/features/films/components/FilmFilter/FilmFilter.tsx
> +    /** Handle search button click. */
please add an empty line

2022-03-22 12:29 UTC, golovachev-yaroslav commented on react/src/features/films/components/FilmFilter/FilmFilter.tsx
> +            onChange={e => setSearchText(e.target.value)}
It would be better to move this function as `handleSearchText`

2022-03-22 12:29 UTC, golovachev-yaroslav commented on react/src/features/films/components/FilmFilter/FilmFilter.tsx
> +            <IconButton size="small" onClick={() => handleSortClick()}>
You can reduce 
`<IconButton size="small" onClick={handleSortClick}>`

2022-03-22 12:29 UTC, golovachev-yaroslav commented on react/src/features/films/components/FilmFilter/FilmFilter.tsx
> +            <IconButton size="small" onClick={() => handleSearchClick()}>
Please reduce onClick

2022-03-22 12:29 UTC, golovachev-yaroslav commented on react/src/features/films/pages/FilmsPage/FilmsPage.tsx
> +          <FilmList films={films} onLoadMore={() => handleLoadMore()} />
`onLoadMore={handleLoadMore}`

2022-03-22 13:19 UTC, timofei-maximov-saritasa commented on react/src/features/films/hooks/use-intersection-observer.ts
> +    const hasIOSupport = !!window.IntersectionObserver;
Make this more explicit.

2022-03-22 13:21 UTC, timofei-maximov-saritasa commented on react/src/features/films/components/FilmFilter/FilmFilter.tsx
> +  const handleSortDirectionChange = setSortDirection;
You have different event handling functions everywhere, let's come up with signle solution

2022-03-22 13:29 UTC, timofei-maximov-saritasa commented on react/src/features/films/components/FilmList/FilmList.tsx
> +      {(filmStatus === 'loading' || true) && <CircularProgress />}
And what about filmStatus? Isn't it an overkill? Usually, we have `loading`, `data` and `error` in our redux store. I think this is enough for your project.

2022-03-23 03:26 UTC, golovachev-yaroslav approved these changes

2022-03-23 09:41 UTC, golovachev-yaroslav approved these changes

2022-03-23 09:41 UTC, golovachev-yaroslav commented on react/src/features/films/components/Sidebar/Sidebar.tsx
> +    if (filmStatus !== 'loading') {
maybe use loading as a const?
`export const LOADING = 'loading';`

2022-03-25 03:21 UTC, panov-aleksey-saritasa approved these changes

2022-03-25 03:21 UTC, panov-aleksey-saritasa commented on react/src/features/films/components/Sidebar/Sidebar.module.css
> +  width: var(--width, 360px);
Not sure why you need second argument here

2022-03-25 08:17 UTC, artem-sotnichenko-saritasa commented on react/src/api/dtos/film.dto.ts
> +export interface FilmDto extends FilmDocument, FirestoreWrapper {}
I use `FilmDocument` to type what firestore functions returns, then map (add id field) it to `EntityDto`.
I think `{ fields: {}, ... }` isn't specific for firestore, but rather for a document in firestore.
So I lean towards this:
```ts
interface FilmData {}
export type FilmDocument = FirestoreDocument<FilmData>;
export type FilmDto = FirestoreDto<FilmDocument>;
```

2022-03-25 12:16 UTC, danilkukryakov approved these changes

2022-03-25 12:16 UTC, danilkukryakov commented on react/src/features/films/hooks/use-intersection-observer.ts
> +    return () => observer.disconnect();
Maybe just `return observer.disconnect;`
Besides, I guess consistent return for linter might be achieved using no-op function like this:
```ts
if (!hasIOSupport || !node) return () => {};
// ...
return observer.disconnect;
```

2022-03-25 12:16 UTC, danilkukryakov commented on react/src/theme/tokens.css
> +  --size-12: 48px;
Maybe if these values are just a scale of base value we can use `calc` like this:
```css
--size-1: 4px;
--size-2: calc(2 * var(--size-1));
--size-2: calc(3 * var(--size-1));
/* etc. */
```
It will help other developers get the idea of how sizes are calculated and they are not just random numbers.

2022-03-25 12:16 UTC, danilkukryakov commented on react/src/index.tsx
>  import '@fontsource/roboto/700.css';
Maybe import these fonts inside CSS? (if it's possible)

2022-03-25 12:16 UTC, danilkukryakov commented on react/src/features/films/components/Sidebar/Sidebar.tsx
> +      <div className={cls['list-wrap']}>
Your approach is fine but for consistency concerns I would rather stick to camelCase naming for CSS classes. So we can use it like `cls.listWrap`.
Anyway, I'm not sure if we have a strict guideline for this.

2022-03-25 12:16 UTC, danilkukryakov commented on react/src/api/mappers/film.mapper.ts
> +export namespace FilmMapper {
Using namespace for mapper is a good approach. However, it has some drawbacks comparing to Angular mappers solution.
Check my [comment](https://github.com/saritasa-nest/camp-js-2022-artem-timofeev/pull/7#discussion_r835159833) in another review.

2022-03-26 14:23 UTC, artem-sotnichenko-saritasa commented on react/src/features/films/components/Sidebar/Sidebar.tsx
> +      <div className={cls['list-wrap']}>
I was feeling uncomfortable about changing css style of naming classes, but if you saying that it's ok.

2022-03-26 15:01 UTC, merged