Feature/JC19-269 film deletion
saritasa-nest/camp-js-2022-artem-sotnichenko pull request #8
Opened 2022-02-07 03:31 UTC by artem-sotnichenko-saritasa

2022-02-07 03:46 UTC, golovachev-yaroslav approved these changes

2022-02-07 03:46 UTC, golovachev-yaroslav commented on vanilla/src/film/index.html
> +          <button class='film__change is-secondary'>Change</button>
It would be better to add `type="button"`

2022-02-07 04:08 UTC, panov-aleksey-saritasa commented on vanilla/src/film/display-film.ts
> +  const infoEl = document.createElement('div');
Please, [avoid contractions](https://frontendwiki.saritasa.rocks/pages/development/principles/naming.html#avoid-contractions)

2022-02-07 04:08 UTC, panov-aleksey-saritasa commented on vanilla/src/index.html
> +            <option value="fields.release_date">release date</option>
Is `fields.` something related to `Firebase`? I think UI should not know about such things.

2022-02-07 05:29 UTC, timofei-maximov-saritasa approved these changes

2022-02-07 05:34 UTC, golovachev-yaroslav approved these changes

2022-02-07 07:13 UTC, gevorg-gevorgyan-saritasa approved these changes

2022-02-07 07:20 UTC, pavel-romanov8 requested changes

2022-02-07 07:20 UTC, pavel-romanov8 commented on vanilla/src/modal/index.ts
> +  title: string;
I don't see that you are mutating those fields in the function below. Let's make them read-only to be more explicit

2022-02-07 07:20 UTC, pavel-romanov8 commented on vanilla/src/auth/login/index.html
> +      </div>
Can we reduce the number of div wrappers like this:
```
<label>
  <input>
</label>
```
?
That way you can even omit `for` and `id` attributes.

2022-02-08 04:43 UTC, elena-dragunova approved these changes

2022-02-08 05:02 UTC, golovachev-yaroslav approved these changes

2022-02-09 05:06 UTC, dbitkovski approved these changes

2022-02-09 05:10 UTC, merged